### ISSUE TITLE
String value that includes commas in array?

### ISSUE THREAD

**Issue by zo0o0ot** [cemdervis/SharpConfig#109]
I have an array of strings in a configuration file.

StringArray = {Thing1,Thing2,Thing3}

I'm trying to add a string value that includes commas in the string. Example: ".*,MaintWebService,.*,.*"

Is there any way for me to change the delimiter or escape the comma so that it is included in the string?

**Comment by cemdervis** [comment]
Hi, you can set `Configuration.IgnoreInlineComments` to false before loading your configurations. This will instruct the parser to ignore any comments that appear on the same line as a setting. Otherwise use `Configuration.PreferredCommentChar` to change the comment delimiter. You can also change `Configuration.ArrayElementSeparator`, if that should be the issue.
Let me know if that helped.

**Comment by zo0o0ot** [comment]
You're right.  I had an inline comment in my configuration, and that was actually the thing that was blowing things up.
Nonetheless, I appreciate knowing these config properties.
