### ISSUE TITLE
Configuration string indexer related...

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#19]
Sir,

Following code maybe invalid/improper, but it adds 'null' in section collection.

var cfg = new Configuration();
cfg["A"] = new Section("B");

Issue related to set indexer, if "A" section not found.
Some validations will be required for such cases?

Configuration.cs -> public Section this[string name]

                var section = GetSection(name);
                int settingIndex = section != null ? mSections.IndexOf(section) : -1;

                if (settingIndex < 0)
                {
                    // A section with that name does not exist yet; add it.
                    mSections.Add(section); // Must add 'value' ???
                }
                else
                {
                    // A section with that name exists; overwrite.
                    mSections[settingIndex] = section;
                }

Thanks

**Comment by cemdervis** [comment]
Hey, you're correct. In both cases, it should be 'value' instead of 'section'.
In all fairness, there shouldn't even be a setter for Configuration.this[string name], so
I think I'll remove it. Or do you have any use case example?

**Comment by Ketan-Desai** [comment]
Sir,

The issue came to notice when I was just browsing the source.

But I don't understand code something like this works, why?

            var cfg = new Configuration();
            cfg["A"]["B"].StringValue = "C";

Thanks

**Comment by cemdervis** [comment]
That is because SharpConfig uses something called "lazy initialization".
For example, when you write cfg["A"], the [get-indexer in Configuration](https://github.com/cemdervis/SharpConfig/blob/master/SharpConfig/Configuration.cs#L596) gets called, which checks if a section called "A" already exists. If not, it's created and returned. Otherwise the existing section is returned immediately.
The type of the expression cfg["A"] is therefore of Section, and Section in turn offers the same functionality, but with Setting types, see its [get-indexer](https://github.com/cemdervis/SharpConfig/blob/master/SharpConfig/Section.cs#L360).
So when you write...
```csharp
        var cfg = new Configuration();
        cfg["A"]["B"].StringValue = "C";
```
... SharpConfig actually creates the sections and settings for you already, but only once.
That's why the **s**et-indexer for sections and settings does not make much sense and could be removed in the future.

**Comment by Ketan-Desai** [comment]
Very nicely explained.

Thank you, Sir!

**Comment by Ketan-Desai** [comment]
Very nicely explained.

Thank you, Sir!

**Comment by cemdervis** [comment]
You're welcome.
