### ISSUE TITLE
Not an issue as such, but package name beautification :)

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#31]
![folder list](https://cloud.githubusercontent.com/assets/9361090/18275645/887bdad2-7465-11e6-8587-402e6710f713.png)

Sir,

Suggestion to change package name with proper case...
sharpconfig.2.0.1 => SharpConfig.2.0.1

Thanks for such an awesome package, so simple and so useful.

**Comment by cemdervis** [comment]
Hey there, the lower-case naming is still there from the first versions of SharpConfig.
I would want to change the package name, but that would automatically create a new package on NuGet, which many existing users might not notice. For now, it's best if the name stays that way, since it should not be a hindrance SharpConfig's usage. I'll think about a solution for future releases, thanks.
