### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#37]
Hi,

Please check following URL...
https://github.com/cemdervis/SharpConfig/wiki/How-to-add-custom-object-string-conversions

In ConvertToString(), '{', '}' is used to delimit string, but in ConvertFromString(), '[', ']' is used to trim/parse it.

Is it type error or my confusion?

2nd issue is, since it is generic class, why 'object' is used as value in input and as return type?

Thanks

**Comment by cemdervis** [comment]
Hey Ketan-Desai,
thanks for submitting this issue.

1. The documentation is indeed incorrect, it should be "[{0};{1}]".
2. The class itself is not generic, but its base class is, see [here](https://github.com/cemdervis/SharpConfig/blob/master/SharpConfig/ITypeStringConverter.cs#L44).
This is so that you don't have to implement the "ConvertibleType" property (and other things in the future) in your own class. Object is passed because it has to be, there is no other general way. Generic type parameters are out of the question, because [Setting.SetValue(object)](https://github.com/cemdervis/SharpConfig/blob/master/SharpConfig/Setting.cs#L457) exists and is the preferred method to use. The generic overloads of SetValue may be removed in the future, as they have provided little benefit.

**Comment by cemdervis** [comment]
Fixed the documentation.
