### ISSUE TITLE
Some clarification regarding formatting rules.

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#59]
Sir,

There are different formatting and output style in various SharpConfig releases.

Please clarify if this are true...

1. Setting and value are separated by one or more space, equal sign, one or more space?
2. All values are escaped by quote or no quote.
3. To get leading and trailing space in String use StringValue.

and finally, how to get leading and trailing space in StringArray?

RowValue split by comma?

Thanks

**Comment by Ketan-Desai** [comment]
I mean, please specify the formatting rules for values, arrays, row value, and how to use special characters like space, double quotes, comma, and arrays.

Thanks

**Comment by Ketan-Desai** [comment]
*row => raw

**Comment by Ketan-Desai** [comment]
*and => in

**Comment by Ketan-Desai** [comment]
I mean, please specify the formatting rules for values, arrays, raw value, and how to use special characters like space, double quotes, a comma in arrays.

Thanks

**Comment by cemdervis** [comment]
Hi, yes, there are different styles between different SharpConfig versions. This is because the formatting was inconsistent in the past regarding arrays and non-arrays, and parsing could lead to unexpected errors.
From now on, the styling will stay as is:

1. Setting name and value are **not** separated by a space anymore. This is because certain applications don't expect a space there, and in turn can't read the config file. SharpConfig had to be changed to be compatible with as many applications as possible.
2. **All** values are escaped from now on. I will release a fix shortly. So:

> Single values are always quoted: ```mySetting="True"```, ```mySetting=" my string with with spaces    "```

> Array values are enclosed by braces, and their elements are quoted like single values: ```myArray={"0","1","2","3"}```

The current SharpConfig version (3.2.1) has a bug which leads to arrays being saved like this: ```myArray="{0,1,2,3}"```. I will release a fix shortly.

3. SharpConfig will not trim any spaces anymore, when the value is quoted. You should always use StringValue if you want to get the value as a string. StringValueTrimmed is obsolete and should not be used anymore.

You will get leading and trailing spaces in StringValueArray with version 3.2.2.

What do you mean by "RowValue split by comma?" ?

Cheers

**Comment by cemdervis** [comment]
Fixed with version 3.2.2. Please open another issue for other questions.

**Comment by Ketan-Desai** [comment]
// Save file...

            var cfg = new Configuration();

            cfg["Section"]["Setting"].StringValueArray = new[] { " 1 ", "2" };

            cfg.SaveToFile(@"d:\sample.txt");

// Sample.txt
[Section]
Setting="{ 1 ,2}"

// Read
            var cfg = Configuration.LoadFromFile(@"d:\sample.txt");

            var array = cfg["Section"]["Setting"].StringValueArray;

            foreach (var item in array)
            {
                Console.WriteLine(string.Format("[{0}]", item));
            }

// Output (spaces trimmed)
[1]
[2]

// RawValue

{ 1 ,2}

This is checked with version 3.2.2

**Comment by cemdervis** [comment]
Fixed with updated 3.2.2. Thanks for finding this bug.

**Comment by mahoganysatsuma** [comment]
> All values are escaped from now on. I will release a fix shortly. So:

Is it possible to turn this off? Or will my single values always be setting="value"?

**Comment by cemdervis** [comment]
For now, it will always be that way to ensure consistency across all setting types. A flag to turn it off might be possible though, in the next release. Do you have issues with quoted single values?

**Comment by mahoganysatsuma** [comment]
We're in the process of slowly getting rid of some legacy ini files, so i'm making a new tool to read/write them. I want to keep them as they are being used in the legacy system, which is without quoting the values (didn't check if it doesnt work just yet, but it's not possible to change the legacy system to handle the quotes properly). So for me it would be useful have a flag/config option like that (or some other way to overrule default quoting)

**Comment by cemdervis** [comment]
I'll figure out a solution for that. Expect another minor release.

**Comment by mahoganysatsuma** [comment]
Cool thanks :)

**Comment by cemdervis** [comment]
@mahoganysatsuma Fixed with version 3.2.3. Let me know if anything is still broken.

**Comment by mahoganysatsuma** [comment]
Impressed by how quick you're picking this up 👍  I'll try it out tomorrow :)
