### ISSUE TITLE
GetValue<string[]>() cause an Exception: cannot convert "System.Object[]" to "System.String[]"

### ISSUE THREAD

**Issue by viruscamp** [cemdervis/SharpConfig#6]
var c= conf["a"]["b"].GetValue<string[]>();

cause an Exception: cannot convert "System.Object[]" to "System.String[]"

**Comment by cemdervis** [comment]
Could you post an example config with that?

**Comment by viruscamp** [comment]
Sorry.
var c= conf["a"]["b"].GetValue<string[]>();
The statement above cause the exception.

[a]
b={abc,def}

**Comment by cemdervis** [comment]
Are you sure your call to GetValue is correct? GetValue normally requires a parameter (the type).

**Comment by cemdervis** [comment]
I think you tried to use GetValue(typeof(string[])) or GetValue<string[]>()?
If so, that wouldn't work (not implemented yet). But what you can do is, get the value as an object array and then convert it to a string array or treat all elements as strings. Example:

var objArray = conf["a"]["b"].GetValue<object[]>();

// If you have access to C# Lambdas.
// If not, convert all elements manually.
var myStrings = Array.ConvertAll(objArray, o => { return o.ToString(); });

// Otherwise, treat every element as a string.
var myString = (string)objArray[...];
