### ISSUE TITLE
Configuration.IgnoreInlineComment is ignored when saving

### ISSUE THREAD

**Issue by cemdervis** [cemdervis/SharpConfig#63]

**Comment by cemdervis** [comment]
Fixed with version 3.2.5.

**Comment by mahoganysatsuma** [comment]
Works great, thanks :)

One thing though, (doesn't matter for my purposes) but I saw that you changed the if statement to the following:
`(rawValue.IndexOf(" ") >= 0 || (rawValue.IndexOfAny(Configuration.ValidCommentChars) >= 0) && !Configuration.IgnoreInlineComments))`
whereas the suggested code was:
`(rawValue.IndexOf(" ") >= 0) || ((rawValue.IndexOfAny(Configuration.ValidCommentChars) >= 0) && !(Configuration.IgnoreInlineComments)))`

I always add the additional (), even when not strictly needed, because order of evaluation is usually annoying to read comprehensively (i.e. what happens first >=, ||, &&, left to right? right to left?), but in your version with less brackets i believe, when you have IgnoreInlineComments=true, you'll ignore values with spaces too now. I dont know if that was intended.

**Comment by cemdervis** [comment]
That's correct, I've misplaced the parenthesis.
