### ISSUE TITLE
No Longer Compatible in Unity

### ISSUE THREAD

**Issue by jamesh38** [cemdervis/SharpConfig#66]
Imported to assets folder in my Unity project and getting compilation errors due to C# features in the code. Any fix for this? If not maybe update wiki. Would love to use the package for my game.

**Comment by cemdervis** [comment]
The fix is to add the SharpConfig assembly to your Unity project ([as a reference](https://docs.unity3d.com/Manual/UsingDLL.html)). It seems that the compiler shipped with Unity cannot recognize C# 5+ features. The assembly is still targeted towards .NET 2.0 however, so it should work out of the box.
You can find the SharpConfig assembly in the respository's **bin** folder.

**Comment by jamesh38** [comment]
Man, I was at that page and was going to do this then thought "no I don't think a compiled version would make a difference." ha! New to C# programming and boy was I wrong. Thanks for the reply! Getting it up and running now.

**Comment by cemdervis** [comment]
Hey man, sure thing, glad I could help. Cheers!
